## Array using Numpy

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [2]:
type(arr)

numpy.ndarray

In [3]:
import numpy as np
arr=np.array(['a','b','c'])
arr
            
              


array(['a', 'b', 'c'], dtype='<U1')

### Two dimensional array

In [4]:
import numpy as np
#two dimensional array
arr=np.array([[1,2,3,4,5], [1,2,3,4,5], 
             [1,2,3,4,5],[1,2,3,4,5]])
arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [5]:
import numpy as np
a= np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [6]:
b=np.zeros(3)
b

array([0., 0., 0.])

In [7]:
c=np.ones(5)
c

array([1., 1., 1., 1., 1.])

In [8]:
d=np.empty(2)
d

array([-2.54786897e+271, -9.11404625e+121])

In [9]:
e=np.arange(8)
e

array([0, 1, 2, 3, 4, 5, 6, 7])

In [10]:
f=np.arange(3,15)
f

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
g=np.arange(3,15,3)
g

array([ 3,  6,  9, 12])

In [12]:
h=np.linspace(3,25,num=3)
h

array([ 3., 14., 25.])

In [13]:
i= np.zeros((2,4))
i

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
j=np.ones((3,4))
j

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
import numpy as np
k=np.empty((2,5))
k

array([[1.29441743e-312, 2.37663529e-312, 2.35541533e-312,
        2.14321575e-312, 8.48798317e-313],
       [1.08221785e-312, 1.10343781e-312, 8.70018274e-313,
        2.24931554e-312, 2.22522597e-306]])

In [16]:
l=np.ones(4, dtype=np.float64)
l

array([1., 1., 1., 1.])

# 3-D Array

In [17]:
m= np.arange(12).reshape(2,2,3)
m

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [18]:
n= np.arange(18).reshape(2,3,3)
n

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [19]:
type(n)

numpy.ndarray

In [20]:
len(n)

2

In [21]:
len(e)

8

In [22]:
len(m)

2

In [25]:
n[1][1]

array([12, 13, 14])

In [27]:
n.mean()

8.5

In [29]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
np.arange(2, 20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [31]:
np.arange(2, 20, 3)

array([ 2,  5,  8, 11, 14, 17])

In [34]:
# Table of 3
np.arange(3,100, 3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [37]:
# Line space
np.linspace(0,100,num=30)

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

# Array functions

In [44]:
aa=np.array([35, 54, 20, 34])
aa

array([35, 54, 20, 34])

In [46]:
aa.sort()
aa

array([20, 34, 35, 54])

In [55]:
con=np.concatenate((f, aa))

In [56]:
con.sort()
con

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 20, 34, 35, 54])

## 2-D array

In [58]:
twod= np.array([[1,2,3,4], [5,6,7,8]])

In [61]:
type(twod)

numpy.ndarray