# How to install 


# pip install pandas
# pip install numpy

In [45]:
import pandas as pd
import numpy as np
# object Creation
s = pd.Series([1,2,3, np.nan,4,5])
s

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    5.0
dtype: float64

In [46]:
dates = pd.date_range("20220103", periods=6)
dates

DatetimeIndex(['2022-01-03', '2022-01-04', '2022-01-05', '2022-01-06',
               '2022-01-07', '2022-01-08'],
              dtype='datetime64[ns]', freq='D')

In [47]:
df = pd.DataFrame(np.random.randn(6, 4), index= dates, columns=list("WXYZ"))
df

W         X         Y         Z
2022-01-03 -0.431413  0.111686  0.659032 -0.988077
2022-01-04 -1.194274  0.177681  0.291841 -0.317466
2022-01-05 -1.021455 -1.027052 -0.006381 -0.685677
2022-01-06 -0.655990  0.139328  0.106849  0.639662
2022-01-07  1.919268  0.254455  0.318627 -0.522071
2022-01-08  0.094651  0.348595  0.530647  0.302870

In [48]:
df2 = pd.DataFrame(
    {
        "A": 2.5,
        "B": pd.Timestamp("20220317"),
        "C": pd.Series(1, index= list(range(4)), dtype= "float32"),
        "D": np.array([3]*4, dtype= "int32"),
        "E": pd.Categorical(["Inam", "Rehman", "Inam", "Rehman"]),
        "F": "Students"
    }
)
df2

A          B    C  D       E         F
0  2.5 2022-03-17  1.0  3    Inam  Students
1  2.5 2022-03-17  1.0  3  Rehman  Students
2  2.5 2022-03-17  1.0  3    Inam  Students
3  2.5 2022-03-17  1.0  3  Rehman  Students

In [49]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [50]:
df.head(2)

W         X         Y         Z
2022-01-03 -0.431413  0.111686  0.659032 -0.988077
2022-01-04 -1.194274  0.177681  0.291841 -0.317466

In [51]:
df.tail(2)

W         X         Y         Z
2022-01-07  1.919268  0.254455  0.318627 -0.522071
2022-01-08  0.094651  0.348595  0.530647  0.302870

In [52]:
df.index

DatetimeIndex(['2022-01-03', '2022-01-04', '2022-01-05', '2022-01-06',
               '2022-01-07', '2022-01-08'],
              dtype='datetime64[ns]', freq='D')

In [53]:
df2.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [54]:
df.to_numpy()

array([[-0.43141315,  0.11168592,  0.65903214, -0.98807727],
       [-1.1942737 ,  0.17768065,  0.29184085, -0.31746569],
       [-1.02145511, -1.02705162, -0.00638111, -0.68567724],
       [-0.65599031,  0.13932793,  0.1068485 ,  0.6396622 ],
       [ 1.91926825,  0.25445461,  0.318627  , -0.52207084],
       [ 0.09465105,  0.34859453,  0.53064664,  0.30286969]])

In [55]:
df2.to_numpy()

array([[2.5, Timestamp('2022-03-17 00:00:00'), 1.0, 3, 'Inam',
        'Students'],
       [2.5, Timestamp('2022-03-17 00:00:00'), 1.0, 3, 'Rehman',
        'Students'],
       [2.5, Timestamp('2022-03-17 00:00:00'), 1.0, 3, 'Inam',
        'Students'],
       [2.5, Timestamp('2022-03-17 00:00:00'), 1.0, 3, 'Rehman',
        'Students']], dtype=object)

In [56]:
df.describe()

W         X         Y         Z
count  6.000000  6.000000  6.000000  6.000000
mean  -0.214869  0.000782  0.316769 -0.261793
std    1.140319  0.510794  0.249802  0.617977
min   -1.194274 -1.027052 -0.006381 -0.988077
25%   -0.930089  0.118596  0.153097 -0.644776
50%   -0.543702  0.158504  0.305234 -0.419768
75%   -0.036865  0.235261  0.477642  0.147786
max    1.919268  0.348595  0.659032  0.639662

In [57]:
df2.T

0                    1                    2  \
A                  2.5                  2.5                  2.5   
B  2022-03-17 00:00:00  2022-03-17 00:00:00  2022-03-17 00:00:00   
C                  1.0                  1.0                  1.0   
D                    3                    3                    3   
E                 Inam               Rehman                 Inam   
F             Students             Students             Students   

                     3  
A                  2.5  
B  2022-03-17 00:00:00  
C                  1.0  
D                    3  
E               Rehman  
F             Students

In [58]:
df.sort_index(axis=1, ascending=False)

Z         Y         X         W
2022-01-03 -0.988077  0.659032  0.111686 -0.431413
2022-01-04 -0.317466  0.291841  0.177681 -1.194274
2022-01-05 -0.685677 -0.006381 -1.027052 -1.021455
2022-01-06  0.639662  0.106849  0.139328 -0.655990
2022-01-07 -0.522071  0.318627  0.254455  1.919268
2022-01-08  0.302870  0.530647  0.348595  0.094651

In [59]:
df.sort_index(axis=1, ascending=True)

W         X         Y         Z
2022-01-03 -0.431413  0.111686  0.659032 -0.988077
2022-01-04 -1.194274  0.177681  0.291841 -0.317466
2022-01-05 -1.021455 -1.027052 -0.006381 -0.685677
2022-01-06 -0.655990  0.139328  0.106849  0.639662
2022-01-07  1.919268  0.254455  0.318627 -0.522071
2022-01-08  0.094651  0.348595  0.530647  0.302870

In [60]:
df.sort_values(by="Y")

W         X         Y         Z
2022-01-05 -1.021455 -1.027052 -0.006381 -0.685677
2022-01-06 -0.655990  0.139328  0.106849  0.639662
2022-01-04 -1.194274  0.177681  0.291841 -0.317466
2022-01-07  1.919268  0.254455  0.318627 -0.522071
2022-01-08  0.094651  0.348595  0.530647  0.302870
2022-01-03 -0.431413  0.111686  0.659032 -0.988077

In [61]:
df["X"]

2022-01-03    0.111686
2022-01-04    0.177681
2022-01-05   -1.027052
2022-01-06    0.139328
2022-01-07    0.254455
2022-01-08    0.348595
Freq: D, Name: X, dtype: float64

In [63]:
df2.to_numpy


<bound method DataFrame.to_numpy of      A          B    C  D       E         F
0  2.5 2022-03-17  1.0  3    Inam  Students
1  2.5 2022-03-17  1.0  3  Rehman  Students
2  2.5 2022-03-17  1.0  3    Inam  Students
3  2.5 2022-03-17  1.0  3  Rehman  Students>

In [64]:
df.to_numpy 

<bound method DataFrame.to_numpy of                    W         X         Y         Z
2022-01-03 -0.431413  0.111686  0.659032 -0.988077
2022-01-04 -1.194274  0.177681  0.291841 -0.317466
2022-01-05 -1.021455 -1.027052 -0.006381 -0.685677
2022-01-06 -0.655990  0.139328  0.106849  0.639662
2022-01-07  1.919268  0.254455  0.318627 -0.522071
2022-01-08  0.094651  0.348595  0.530647  0.302870>

In [65]:
df.to_numpy()

array([[-0.43141315,  0.11168592,  0.65903214, -0.98807727],
       [-1.1942737 ,  0.17768065,  0.29184085, -0.31746569],
       [-1.02145511, -1.02705162, -0.00638111, -0.68567724],
       [-0.65599031,  0.13932793,  0.1068485 ,  0.6396622 ],
       [ 1.91926825,  0.25445461,  0.318627  , -0.52207084],
       [ 0.09465105,  0.34859453,  0.53064664,  0.30286969]])